Feature/#2:view-viewgroup
temnik15/AndroidAcademyProject pull request #1
Opened 2020-11-29 11:58 UTC by temnik15

Made up the MovieDetails screen. Added required resources and permissions. Created a fake data display.
![Z-b3laNu9MU](https://user-images.githubusercontent.com/45372245/100541210-44a0df00-3253-11eb-8df6-e819e2c18a13.jpg)

2020-11-29 20:08 UTC, nikslushkin requested changes

2020-11-29 20:08 UTC, nikslushkin commented on app/src/main/java/ru/rosystem/androidacedemyproject/ui/movieDetails/MovieDetailsActivity.kt
> +import kotlinx.android.synthetic.main.activity_movie_details.*
It is cool that you are trying new ways to work with views.
Unfortunately it is not recommended way. 
I'm afraid you have to refactor it to https://developer.android.com/topic/libraries/view-binding

2020-11-29 20:08 UTC, nikslushkin commented on app/src/main/java/ru/rosystem/androidacedemyproject/ui/movieDetails/MovieDetailsActivity.kt
> +        genres.text = builder.toString().subSequence(0, builder.length - 2)
it is java way to concatenate strings. Try to find more kotlin-like

2020-11-29 20:08 UTC, nikslushkin commented on app/src/main/res/layout/cast_list_item.xml
> +    tools:background="#191926">
i recommend you extract it to colors.xml

2020-11-29 20:08 UTC, nikslushkin commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:textSize="@dimen/text_size_12"
I recommend you to extract attributes to styles

2020-11-29 20:16 UTC, nikslushkin commented
![image](https://user-images.githubusercontent.com/1586158/100552539-b15caf00-323c-11eb-9566-ac295388ea72.png)
Try to implement it close to design

2020-11-29 20:18 UTC, nikslushkin commented
good job! let's improve it

2020-11-30 17:04 UTC, temnik15 commented on app/src/main/java/ru/rosystem/androidacedemyproject/entity/Actor.kt
> +data class Actor(val name:String,val photoUrl:String)
Ok, I will add ktlint separately

2020-11-30 17:04 UTC, temnik15 commented on app/src/main/java/ru/rosystem/androidacedemyproject/entity/Genres.kt
> +}
Yes, it's a problem. I will change to receive data from the server.

2020-11-30 17:15 UTC, temnik15 commented on app/src/main/java/ru/rosystem/androidacedemyproject/repository/MovieRepositoryImpl.kt
> +    private val movie: Movie
ok, changed :)

2020-11-30 17:16 UTC, temnik15 commented on app/src/main/java/ru/rosystem/androidacedemyproject/ui/movieDetails/MovieDetailsActivity.kt
> +        genres.text = builder.toString().subSequence(0, builder.length - 2)
Since I got rid of enum, concatenation is not needed yet.

2020-12-04 12:15 UTC, temnik15 commented on app/src/main/java/ru/rosystem/androidacedemyproject/ui/movieDetails/MovieDetailsActivity.kt
> +import kotlinx.android.synthetic.main.activity_movie_details.*
Ok, I'll replace it with the binding type in a separate pr.

2020-12-04 12:20 UTC, temnik15 commented
Adjusted the design to be closer to the layout, but failed to achieve 100% match (
![end](https://user-images.githubusercontent.com/45372245/101163005-2e749380-3644-11eb-8822-155a1af1ee24.PNG)

2020-12-04 15:34 UTC, Pavel-Sidorovich commented on app/src/main/res/values/styles.xml
> +        <item name="background">@drawable/age_back</item>
Something is wrong

2020-12-04 15:42 UTC, Pavel-Sidorovich commented on app/src/main/res/layout/activity_movie_details.xml
> +            app:layout_constraintTop_toTopOf="parent" />
Maybe you can combine it

2020-12-04 15:45 UTC, Pavel-Sidorovich commented on app/src/main/res/values/dimens.xml
> +    <dimen name="actor_photo_side">90dp</dimen>
Why 90?

2020-12-04 15:47 UTC, Pavel-Sidorovich commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_marginTop">@dimen/space_36</item>
Maybe less?

2020-12-04 15:47 UTC, Pavel-Sidorovich commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_marginTop">@dimen/space_default</item>
Maybe less?

2020-12-04 15:56 UTC, Pavel-Sidorovich commented
You can do better than this
<img src="https://user-images.githubusercontent.com/10943612/101184614-fbd99380-3661-11eb-80c6-02c7f22057d7.jpg" width="45%">
For example so
<img src="https://user-images.githubusercontent.com/10943612/101184682-0e53cd00-3662-11eb-8a7c-29fb6498c65f.jpg" width="45%">

2020-12-04 17:03 UTC, temnik15 commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_marginTop">@dimen/space_36</item>
agree, need less

2020-12-04 17:06 UTC, temnik15 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="actor_photo_side">90dp</dimen>
but no, I solved the problem

2020-12-04 17:31 UTC, temnik15 commented
it turned out a little better
![new](https://user-images.githubusercontent.com/45372245/101194869-a5735180-366f-11eb-9ede-84dd7a18d4c5.png)

2020-12-04 17:34 UTC, temnik15 commented on app/src/main/res/layout/activity_movie_details.xml
> +            app:layout_constraintTop_toTopOf="parent" />
I'll make it a separate branch.

2020-12-04 21:19 UTC, NikitaVladimirovich commented on app/src/main/res/values/dimens.xml
> +    <dimen name="space_6">6dp</dimen>
Maybe name it in one style?

2020-12-04 21:23 UTC, NikitaVladimirovich commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_marginTop="@dimen/space_14"
Why 14?

2020-12-04 21:28 UTC, NikitaVladimirovich commented on app/src/main/res/drawable/path.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Why you named the file so?

2020-12-04 21:36 UTC, NikitaVladimirovich commented on app/src/main/java/ru/rosystem/androidacedemyproject/ui/movieDetails/MovieDetailsActivity.kt
> +
remove empty lines

2020-12-04 21:38 UTC, NikitaVladimirovich commented on app/src/main/java/ru/rosystem/androidacedemyproject/ui/movieDetails/CastAdapter.kt
> +        notifyDataSetChanged()
What about DiffUtil from the lectures?

2020-12-04 21:39 UTC, NikitaVladimirovich commented on app/src/main/java/ru/rosystem/androidacedemyproject/repository/MovieRepositoryImpl.kt
> +
remove empty lines everywhere

2020-12-04 21:41 UTC, NikitaVladimirovich commented on app/src/main/res/values/styles.xml
> +        <item name="layoutManager">LinearLayoutManager</item>
Do you really need it?

2020-12-04 21:45 UTC, NikitaVladimirovich commented on app/src/main/res/values/styles.xml
> +        <item name="layout_constraintDimensionRatio">375:298</item>
Maybe put it into **dimens**?

2020-12-04 21:47 UTC, NikitaVladimirovich commented
Why you use mask.png instead of vector-drawable?

2020-12-05 16:22 UTC, temnik15 commented on app/src/main/res/values/styles.xml
> +        <item name="layout_constraintDimensionRatio">375:298</item>
Moved into resources (constraintDimensionRatio takes a string)

2020-12-05 16:24 UTC, temnik15 commented on app/src/main/res/values/styles.xml
> +        <item name="layoutManager">LinearLayoutManager</item>
There is a manual installation in the code anyway. It is really necessary here, otherwise the preview recycler is displayed incorrectly

2020-12-05 16:26 UTC, temnik15 commented on app/src/main/java/ru/rosystem/androidacedemyproject/ui/movieDetails/CastAdapter.kt
> +        notifyDataSetChanged()
It will be replaced in a separate pull request so as not to clutter up the current one.

2020-12-05 16:27 UTC, temnik15 commented on app/src/main/res/drawable/path.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
renamed by meaning

2020-12-05 16:29 UTC, temnik15 commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:layout_marginTop="@dimen/space_14"
Otherwise, it will not match the layout. I'll try to fix

2020-12-05 16:31 UTC, temnik15 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="space_6">6dp</dimen>
Changed

2020-12-05 16:49 UTC, temnik15 commented
There was a problem, so I decided to cheat a little, took a mask from Figma

2020-12-05 17:48 UTC, temnik15 commented
![tmp](https://user-images.githubusercontent.com/45372245/101259649-20ee0500-373b-11eb-8a51-520125177c76.png)

2020-12-05 21:11 UTC, temnik15 commented
I really do not understand why it is not possible to display the view normally for PG (ageLimit) If width = heigth=24dp is set then the view is slightly smaller when overlaid. I decided as best I could). On the whole, I am satisfied with the result.
![result](https://user-images.githubusercontent.com/45372245/101265429-720bf200-3757-11eb-8136-d867bc448a15.png)

2020-12-06 22:46 UTC, nikslushkin approved these changes

2020-12-07 07:46 UTC, NikitaVladimirovich approved these changes

2020-12-07 07:46 UTC, NikitaVladimirovich commented on app/src/main/res/layout/cast_list_item.xml
> +    <androidx.cardview.widget.CardView
Change the card background. When the photo not loaded yet, the white square is shown.

2020-12-07 07:46 UTC, NikitaVladimirovich commented on app/src/main/res/layout/activity_movie_details.xml
> +        <androidx.recyclerview.widget.RecyclerView
Maybe use horizontal padding and clipToPadding=false ? 

<img width="205" alt="Screenshot 2020-12-07 at 10 40 29" src="https://user-images.githubusercontent.com/15379601/101322790-a7f4c780-3878-11eb-9073-29f4eccf57ef.png">

2020-12-07 08:08 UTC, merged